version: '3'
services:
  flask:
    container_name: flask
    build: .
    command: python -u app.py
    ports:
      - 8000:8000
    links:
      -  mongo  

  mongo:
    image : mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017